import fs from "node:fs";
import path from "node:path";
import { load } from "cheerio";

const root = process.cwd();
const pagesRoot = path.join(root, "source-site/pages");
const assetsRoot = path.join(root, "public/prismtec-assets");

const read = (p) => fs.readFileSync(path.join(pagesRoot, p), "utf8");
const toAsset = (s = "") => {
  const clean = s.replace(/^\.\.\//, "").replace(/^\//, "");
  return `/prismtec-assets/${clean}`;
};
const toSlug = (s) => s.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

const aboutHtml = read("about-us.html.html");
const $about = load(aboutHtml);
const aboutParagraphs = $about(".rs-about .sec-title .desc").map((_, el) => $about(el).text().replace(/\s+/g, " ").trim()).get();
const aboutRange = $about(".about-red li").map((_, el) => $about(el).text().trim()).get();

const contactHtml = read("contact.html.html");
const $contact = load(contactHtml);
const contactCards = $contact(".contact-box .address-box").map((_, el) => {
  const title = $contact(el).find(".label").first().text().trim();
  const text = $contact(el).find(".address-text").text().replace(/\s+/g, " ").trim();
  return { title, text };
}).get();

const productIndexHtml = read("product.html.html");
const $p = load(productIndexHtml);
const filterMap = {};
$p(".gridFilter button").each((_, el) => {
  const key = $p(el).attr("data-filter")?.replace(".", "") || "all";
  filterMap[key] = $p(el).text().replace(/\s+/g, " ").trim();
});

const productItems = $p(".grid .grid-item").map((_, el) => {
  const classes = ($p(el).attr("class") || "").split(/\s+/);
  const filterClass = classes.find((c) => c.startsWith("filter")) || "";
  const category = filterMap[filterClass] || "Products";
  const a = $p(el).find("a").first();
  const href = a.attr("href") || "";
  const img = $p(el).find("img").first().attr("src") || "";
  const title = $p(el).find(".category a").first().text().replace(/\s+/g, " ").trim();
  return { title, href, image: toAsset(img), category };
}).get();

const productDetails = productItems.map((item) => {
  const detailPath = item.href.replace(/^\.\//, "");
  const filePath = detailPath.endsWith(".html") ? `${detailPath}.html` : `${detailPath}.html.html`;
  const fullFile = path.join(pagesRoot, filePath);
  if (!fs.existsSync(fullFile)) {
    return { ...item, slug: toSlug(item.title), summary: item.title, points: [], video: null };
  }
  const html = fs.readFileSync(fullFile, "utf8");
  const $d = load(html);
  const title = $d(".services-title .title").first().text().replace(/\s+/g, " ").trim() || item.title;
  const summary = $d(".services-single p").first().text().replace(/\s+/g, " ").trim() || title;
  const points = $d(".check-lists li").map((_, li) => $d(li).text().replace(/\s+/g, " ").trim()).get();
  const heroImage = toAsset($d(".services-img img").first().attr("src") || item.image);
  const video = $d("iframe").first().attr("src") || null;
  const categorySlug = toSlug(item.category);
  return { ...item, title, slug: toSlug(title), categorySlug, summary, points, image: heroImage, video };
});

const groupedProducts = {};
for (const p of productDetails) {
  if (!groupedProducts[p.categorySlug]) groupedProducts[p.categorySlug] = [];
  groupedProducts[p.categorySlug].push(p);
}

const allAssetFiles = [];
function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const fp = path.join(dir, e.name);
    if (e.isDirectory()) walk(fp);
    else if (/\.(webp|png|jpe?g|gif)$/i.test(e.name)) allAssetFiles.push(fp);
  }
}
walk(assetsRoot);
const assetPaths = allAssetFiles.map((fp) => `/${path.relative(path.join(root, "public"), fp).replace(/\\/g, "/")}`);

const clientLogos = assetPaths.filter((p) => p.includes("/client-logo/"));
const eventImages = assetPaths.filter((p) => p.includes("/event/"));
const iconImages = assetPaths.filter((p) => p.includes("/icon/"));
const machineImages = assetPaths.filter((p) => p.includes("/products/"));
const factoryImages = assetPaths.filter((p) => p.includes("about-us") || p.includes("Website-Elements") || p.includes("home-banners"));

const output = `/* AUTO-GENERATED BY scripts/generate-content.mjs */
export const generatedContent = ${JSON.stringify({ aboutParagraphs, aboutRange, contactCards, productDetails, groupedProducts, assets: { all: assetPaths, clientLogos, eventImages, iconImages, machineImages, factoryImages } }, null, 2)} as const;
`;

fs.writeFileSync(path.join(root, "src/content/generated.ts"), output);
console.log("Generated src/content/generated.ts");
